export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const REMOVE_SUCCESS_MESSAGE = "REMOVE_SUCCESS_MESSAGE";
