export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const REMOVE_SUCCESS_MESSAGE = "REMOVE_SUCCESS_MESSAGE";
