export const FETCH_ALL_SUBJECTS = "FETCH_ALL_SUBJECTS";
export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const EDITED_SUBJECT = "EDITED_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
